title: Sayn
description: The official site for Sayn and Strange Encounters Sayn. Art, wallpapers, fiction, archives, projects and other material.

url: "https://sayn.cc"
baseurl: ""

author: uvxszi

collections:
  gallery:
    output: true
    permalink: /gallery/:name/

defaults:
  - scope:
      path: ""
      type: gallery
    values:
      layout: gallery-item

exclude:
  - README.md
  - scripts